services:
  photolog:
    build:
      context: .
    container_name: "photolog-app"
    environment:
      SECRET_KEY: "${SECRET_KEY}"
    ports:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photolog.rule=Host(`photolog.tillmannbedau.com`)"
      - "traefik.http.routers.photolog.entrypoints=websecure"
      - "traefik.http.routers.photolog.tls.certresolver=cloudflare"
    volumes:
      - "./uploads:/app/uploads"
      - "./data:/app/data"
    networks:
      - "traefik-public"
    restart: unless-stopped

networks:
  traefik-public:
    external: true
