services:
  photolog:
    build:
      context: .
    container_name: "photolog-app"
    environment:
      SECRET_KEY: "${SECRET_KEY}"
    ports:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photolog.rule=Host(`photolog.tillmannbedau.de`) || Host(`photolog.tillbedau.de`)"
      - "traefik.http.routers.photolog.entrypoints=websecure"
      - "traefik.http.routers.photolog.tls.certresolver=letsencrypt"
    volumes:
      - "./uploads:/app/uploads"
      - "./data:/app/data"
    networks:
      - "traefik-public"
    depends_on:
      - traefik
    restart: unless-stopped

networks:
  traefik-public:
    external: true
