name: Deploy Photolog App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Transfer Application Files to Remote Host
      - name: Deploy Code to Remote Host
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avrh --exclude=data/ --exclude=uploads/ --delete
          path: ./
          remote_path: ${{ secrets.SSH_REMOTE_PATH }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 4: Deploy Application on Remote Host
      - name: Deploy on Remote Host
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SSH_REMOTE_PATH }}

            # Write secrets directly to .env file
            echo "Creating the .env file for Docker..."
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env
            chmod 600 .env
            echo "The .env file has been created."

            docker compose down
            docker compose up -d --build
